package server

import (
	"fmt"
	"html/template"
	"net/http"
	"strings"

	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/cthiel77/server-demo/config"
	"github.com/cthiel77/server-demo/internal"
	"github.com/cthiel77/server-demo/internal/cfg"
	"github.com/cthiel77/server-demo/internal/db"
	"github.com/cthiel77/server-demo/internal/meta"
	"github.com/cthiel77/server-demo/server/handler"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/template/html/v2"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/cthiel77/server-demo/docs"
)

// RunAPIServer runs the server
func RunAPIServer(args []string) {

	engine := html.NewFileSystem(http.FS(config.TemplateFilesEmbedded), ".gohtml")
	engine.Layout("embed")    // Optional. Default: "embed"
	engine.Delims("{{", "}}") // Optional. Default: engine delimiters
	//extend template functions
	engine.AddFuncMap(map[string]any{
		"contains":  strings.Contains,
		"hasPrefix": strings.HasPrefix,
		"hasSuffix": strings.HasSuffix,
	})
	engine.AddFunc("unescape", func(s string) template.HTML {
		return template.HTML(s)
	})

	fbCfg := fiber.Config{
		Views:   engine,
		AppName: meta.App.Name,
	}

	//dev settings
	if cfg.DevModeEnabled() {
		config.Logger.Info("dev mode enabled")
		engine.Reload(true) // Optional. Default: false
		engine.Debug(true)  // Optional. Default: false
	} else {
		config.Logger.Info("prod mode active")
		fbCfg.Prefork = true
		fbCfg.DisableStartupMessage = true
	}

	app := fiber.New(fbCfg)

	// Middlewares
	// add db to context
	config.Logger.Info("starting database")
	if err := db.Run(); err != nil {
		config.Logger.Fatalf("db init error: %+v", err)
	}
	heroQuerystack := db.NewHeroQuerstack(db.DBSession)
	app.Use(func(c *fiber.Ctx) error {
		internal.SetLocal[db.HeroQueryStack](c, "db", heroQuerystack)
		// Go to next middleware:
		return c.Next()
	})
	app.Use(recover.New())

	//▽
	//▽  api endpoints
	//▽
	apiV1 := app.Group("api/v1")
	apiV1.Get("hero", handler.ApiHeroGetAll)
	apiV1.Get("hero/", handler.ApiHeroGetAll)
	apiV1.Get("hero/:id", handler.ApiHeroGetByID)

	if cfg.DevModeEnabled() {
		app.Use(logger.New())

		//enable swagger
		config.Logger.Info("enabling swagger")
		apiV1.Get("swagger", swagger.New(swagger.Config{
			Title:       meta.GetAppName(),
			DeepLinking: true,
		}))
		apiV1.Get("swagger/*", swagger.New(swagger.Config{
			Title:       meta.GetAppName(),
			DeepLinking: true,
		}))
	}

	//▽
	//▽  static files
	//▽
	app.Use("/assets", filesystem.New(filesystem.Config{
		Root:       http.FS(config.StaticFilesEmbedded),
		PathPrefix: "web/static/assets",
		Browse:     false,
	}))

	//▽
	//▽  dynamic files
	//▽
	app.Get("/", handler.PageHome)

	// Handle not founds
	app.Use(handler.Page404)
	//▽
	//▽  run server
	//▽
	config.Logger.Fatal(app.Listen(fmt.Sprintf(":%s", config.App.Server.Port)))
}
