basePath: /api
definitions:
  db.HeroSet:
    properties:
      firstName:
        example: Wade
        type: string
      heroName:
        example: Deadpool
        type: string
      id:
        example: 123
        type: integer
      lastName:
        example: Wilson
        type: string
    type: object
  response.ErrorData:
    properties:
      code:
        example: "10001"
        type: string
      msg:
        example: something went wrong
        type: string
    type: object
info:
  contact:
    email: support@thiel-inet.de
    name: API Support
  description: This is a demonstration application showing a working example of several
    functions and performance features.
  license:
    name: Apache 2.0
    url: https://opensource.org/license/bsd-3-clause/
  termsOfService: http://swagger.io/terms/
  title: server-demo
  version: "1.0"
paths:
  /v1/hero:
    get:
      consumes:
      - application/json
      description: Get all heroes.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.HeroSet'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorData'
      summary: get all heroes
      tags:
      - Hero
  /v1/hero/{id}:
    get:
      consumes:
      - application/json
      description: Get hero by given ID.
      parameters:
      - default: 2
        description: Hero ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.HeroSet'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorData'
      summary: get hero by given ID
      tags:
      - Hero
swagger: "2.0"
